const fs = require('fs');

const content = [
'const express = require("express");',
'const cors = require("cors");',
'const fetch = require("node-fetch");',
'const path = require("path");',
'',
'const app = express();',
'const PORT = process.env.PORT || 3000;',
'const TOKEN = "29757506dbc94ae89ba828dd98fd5f0f";',
'',
'app.use(cors());',
'app.use(express.json());',
'app.use(express.static(path.join(__dirname, "../public")));',
'',
'const logoCache = new Map();',
'const searchCache = new Map();',
'',
'app.get("/api/logo/search", async (req, res) => {',
'  const q = (req.query.q || "").toString().trim();',
'  if (!q || q.length < 2) return res.json([]);',
'  const key = q.toLowerCase();',
'  if (searchCache.has(key)) return res.json(searchCache.get(key));',
'  try {',
'    const r = await fetch("https://api.football-data.org/v4/teams?name=" + encodeURIComponent(q) + "&limit=8", {',
'      headers: { "X-Auth-Token": TOKEN }',
'    });',
'    const data = await r.json();',
'    const teams = (data.teams || []).slice(0, 8).map(t => ({',
'      name: t.shortName || t.name,',
'      country: t.area ? t.area.name : "",',
'      color: "#6366f1",',
'      logo: t.crest || "",',
'      proxyLogo: t.crest ? "/api/logo/img?url=" + encodeURIComponent(t.crest) : ""',
'    }));',
'    searchCache.set(key, teams);',
'    res.json(teams);',
'  } catch (err) {',
'    res.status(500).json([]);',
'  }',
'});',
'',
'app.get("/api/logo/img", async (req, res) => {',
'  const url = req.query.url ? req.query.url.toString() : null;',
'  if (!url) return res.status(400).send("Missing url");',
'  if (logoCache.has(url)) {',
'    const c = logoCache.get(url);',
'    res.set("Content-Type", c.ct);',
'    res.set("Cache-Control", "public, max-age=86400");',
'    res.set("Access-Control-Allow-Origin", "*");',
'    return res.send(c.buf);',
'  }',
'  try {',
'    const r = await fetch(url, {',
'      headers: { "User-Agent": "Mozilla/5.0", "X-Auth-Token": TOKEN }',
'    });',
'    if (!r.ok) return res.status(r.status).send("Upstream error: " + r.status);',
'    const ct = r.headers.get("content-type") || "image/png";',
'    const buf = await r.buffer();',
'    logoCache.set(url, { buf, ct });',
'    res.set("Content-Type", ct);',
'    res.set("Cache-Control", "public, max-age=86400");',
'    res.set("Access-Control-Allow-Origin", "*");',
'    res.send(buf);',
'  } catch (err) {',
'    res.status(500).send("Proxy error");',
'  }',
'});',
'',
'app.get("/", (req, res) => res.sendFile(path.join(__dirname, "../public/index.html")));',
'app.get("/scoreboard", (req, res) => res.sendFile(path.join(__dirname, "../public/overlays/scoreboard.html")));',
'app.get("/tips", (req, res) => res.sendFile(path.join(__dirname, "../public/overlays/tips.html")));',
'app.get("/countdown", (req, res) => res.sendFile(path.join(__dirname, "../public/overlays/countdown.html")));',
'app.get("/probability", (req, res) => res.sendFile(path.join(__dirname, "../public/overlays/probability.html")));',
'app.get("/heatmap", (req, res) => res.sendFile(path.join(__dirname, "../public/overlays/heatmap.html")));',
'app.get("/alert", (req, res) => res.sendFile(path.join(__dirname, "../public/overlays/alert.html")));',
'app.get("/admin", (req, res) => res.sendFile(path.join(__dirname, "../public/admin.html")));',
'',
'app.listen(PORT, () => {',
'  console.log("✅ Stream Overlays running on http://localhost:" + PORT);',
'});'
].join('\n');

fs.writeFileSync('server/index.js', content);
console.log('done');
